export const SET_CHARACTER_LIST = "SET_CHARACTER_LIST";
export const SET_ALL_CHARACTER_LIST = "SET_ALL_CHARACTER_LIST";
export const SET_PAGINATION_OFFSET = "SET_PAGINATION_OFFSET";
export const SET_ACTIVE_CHARACTER = "SET_ACTIVE_CHARACTER";
